In [1]:
!git clone https://github.com/ultralytics/yolov5  # clone repo
!pip install -qr yolov5/requirements.txt  # install dependencies (ignore errors)
%cd yolov5
 
import torch
from IPython.display import Image, clear_output  # to display images
from utils.google_utils import gdrive_download  # to download models/datasets
 
clear_output()
print('Setup complete. Using torch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))

Setup complete. Using torch 1.9.0+cu102 _CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=15109MB, multi_processor_count=40)


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!ls /content/drive/MyDrive/YOLOv5/data

classes.txt  convert_annotations.py  datadownloadv5.ipynb  plate.zip  vtest.avi


In [ ]:
# copy over both datasets into the root directory of the Colab VM (comment out test.zip if you are not using a validation dataset)
!cp /content/drive/MyDrive/YOLOv5/data/Person.zip /content

In [ ]:
# unzip the datasets and their contents so that they are now in /content/darknet/data/ folder
!unzip /content/Person.zip -d /content/

In [ ]:
!python train.py --img 512 --batch 12 --epochs 10 --data /content/drive/MyDrive/YOLOv5/Person.yaml --cfg /content/drive/MyDrive/YOLOv5/yolov5x.yaml --weights yolov5x.pt --name '' #OOM=>記憶體爆掉
#CPU會根本跑不出來

train: weights=yolov5x.pt, cfg=/content/drive/MyDrive/YOLOv5/yolov5x.yaml, data=/content/drive/MyDrive/YOLOv5/Person.yaml, hyp=data/hyps/hyp.scratch.yaml, epochs=10, batch_size=12, img_size=[512], rect=False, resume=False, nosave=False, notest=False, noautoanchor=False, evolve=False, bucket=, cache_images=False, image_weights=False, device=, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=8, project=runs/train, entity=None, name=, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, upload_dataset=False, bbox_interval=-1, save_period=-1, artifact_alias=latest, local_rank=-1
github: up to date with https://github.com/ultralytics/yolov5 ✅
YOLOv5 🚀 v5.0-250-g02719dd torch 1.9.0+cu102 CUDA:0 (Tesla T4, 15109.75MB)

hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s

In [ ]:
!cp 'runs/train/weights/best.pt' /content/drive/MyDrive/YOLOv5/Person
!cp 'runs/train/weights/last.pt' /content/drive/MyDrive/YOLOv5/Person

In [ ]:
%cd /content/yolov5

/content/yolov5


In [73]:
!cp /content/detect.py /content/yolov5

In [68]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b = a.reshape([3,2,2])
b.T.shape

(2, 2, 3)

In [74]:
#!python detect.py --weights runs/train/weights/best.pt --img 512 --conf 0.5 --source '/content/drive/MyDrive/yolo/yolov5/plates.jpg'
!python detect.py --weights /content/drive/MyDrive/YOLOv5/Person/best.pt --img 512 --conf 0.1 --source '/content/drive/MyDrive/YOLOv5/Person/2.jpg' #conf設越高，代表要求越高，一定要抓到某個物件

detect: weights=['/content/drive/MyDrive/YOLOv5/Person/best.pt'], source=/content/drive/MyDrive/YOLOv5/Person/2.jpg, imgsz=512, conf_thres=0.1, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False
YOLOv5 🚀 v5.0-253-g57c5d02 torch 1.9.0+cu102 CUDA:0 (Tesla T4, 15109.75MB)

Fusing layers... 
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Model Summary: 484 layers, 88390614 parameters, 0 gradients, 219

```
this is n: 21
this is s: 384x512 21 Persons,
```

```
[[     381.72      61.106      489.05      390.86     0.51686           0]
 [     226.05      97.953      308.56      386.99      0.4702           0]
 [     462.58      89.911      514.37      375.44     0.37383           0]
 [     47.245       60.94      135.87      270.15     0.32714           0]
 [     235.14      50.515      289.41      139.14     0.27668           0]
 [     440.04      17.192      508.59      126.17     0.25905           0]
 [     7.3263      31.027      85.063      125.32     0.25237           0]
 [     7.7543      102.84      73.067      227.95     0.25222           0]
 [     291.47      40.989      391.76      388.68     0.24149           0]
 [     89.029      47.939      134.35      124.56     0.21343           0]
 [     120.36        20.9      185.86      126.09     0.18757           0]
 [     279.07      52.776      310.22      123.09     0.18297           0]
 [     212.14      104.18       269.3       184.3      0.1768           0]
 [     136.01      66.398      260.03      364.07     0.17182           0]
 [     -0.819      27.361      58.056      209.95     0.16699           0]
 [     218.73      39.852      251.29      90.132      0.1621           0]
 [     122.18      7.6937      145.03      53.046     0.12765           0]
 [     215.34      80.643      279.99       156.2     0.12475           0]
 [     436.24    -0.82732      471.86      67.426     0.11206           0]
 [     104.24      44.642       199.1      309.52     0.10348           0]
 [     196.73      2.6234      426.58      421.81      0.1032           0]]
 ```

In [ ]:
!ls

CONTRIBUTING.md  export.py   __pycache__       test.py	       yolov5x.pt
data		 hubconf.py  README.md	       train.py
detect.py	 LICENSE     requirements.txt  tutorial.ipynb
Dockerfile	 models      runs	       utils


Reference: https://github.com/ultralytics/yolov5

In [ ]:
# https://github.com/ultralytics/yolov5/issues/388

In [ ]:
!git clone https://github.com/ChargedMonk/Social-Distancing-using-YOLOv5.git

Cloning into 'Social-Distancing-using-YOLOv5'...
remote: Enumerating objects: 134, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 134 (delta 5), reused 0 (delta 0), pack-reused 113
Receiving objects: 100% (134/134), 74.78 MiB | 23.02 MiB/s, done.
Resolving deltas: 100% (51/51), done.


In [ ]:
%cd /content/Social-Distancing-using-YOLOv5

/content/Social-Distancing-using-YOLOv5


In [ ]:
!pip install -U -r requirements.txt

  Cloning https://github.com/cocodataset/cocoapi.git to /tmp/pip-req-build-5iphf4_1
  Running command git clone -q https://github.com/cocodataset/cocoapi.git /tmp/pip-req-build-5iphf4_1
Requirement already up-to-date: Cython in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 2)) (0.29.23)
     |████████████████████████████████| 20.3MB 7.2MB/s 
  Using cached https://files.pythonhosted.org/packages/72/b3/3878691fec6babd78bbf4c71c720e1831cbb6ada61679613fe2fae080568/opencv_python-4.5.2.54-cp37-cp37m-manylinux2014_x86_64.whl
Requirement already up-to-date: torch>=1.5 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 5)) (1.9.0+cu102)
  Using cached https://files.pythonhosted.org/packages/24/33/5568d443ba438d95d4db635dd69958056f087e57e1026bee56f959d53f9d/matplotlib-3.4.2-cp37-cp37m-manylinux1_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/33/34/542152297dcc6c47a9dcb0685eac6d652d878ed3cea83bf2b23cb988e857/Pillow-8.2.0-cp37-cp3

In [ ]:
!python detect.py --source ./inference/videos/vtest.avi


Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', fourcc='mp4v', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='./inference/videos/vtest.avi', view_img=False, weights='weights/yolov5s.pt')
Using CUDA device0 _CudaDeviceProperties(name='Tesla K80', total_memory=11441MB)

/usr/local/lib/python3.7/dist-packages/torch/serialization.py:671: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.7/dist-packages/torch/serialization.py:671: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = Tru

In [ ]:
!cp /content/drive/MyDrive/YOLOv5/data/vtest.avi /content/Social-Distancing-using-YOLOv5/inference/videos

In [ ]:
# download the video with detections shown
from google.colab import files

video_path = '/content/Social-Distancing-using-YOLOv5/inference/output/vtest.avi'
files.download(video_path)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>